dist: trusty
sudo: required

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ubuntu-sdk-team/ppa
          packages:
            - gcc-5
            - g++-5
            - git
      env: COMPILER=g++-5

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/3rdParty_install.sh; fi
  - git submodule update --init
  - export COVERALLS_SERVICE_NAME=travis-ci

before_script:
  # use gcc-5 & g++-5
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - gcc --version
  - g++ --version
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=AozuIr30I43ZXIG5ddfoPejrK7KtkmltS

script:
  # Display cmake version
  - cmake --version
  # Create build folder
  - rm -rf build
  - mkdir build
  - cd build
  # cmake
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON ..
  # limit GCC builds to a reduced number of thread for the virtual machine
  - time make all -j2
  - make coveralls
  - cat coveralls.json
